### ISSUE TITLE
I may have found a bug.

### ISSUE THREAD

**Issue by pharry22** [piranout/Funcular.IdGenerators#1] opened 2015-08-27 03:02 UTC
In the BaseConverter Convert method, if the number passed in is 06-0E-3C-01-59 then the method falls over on this line.

``` c#
result = CharList[value] + result;
```

with this exception:

``` c#
System.IndexOutOfRangeException: Index was outside the bounds of the array.
```

As the value of "value" is some large negative number.
I have "fixed" the problem by changing the negative number to a positive number in the for loop but I don't know if that is a valid fix.

``` c#
else if (newlen > 0)
                    {
                        if (newlen == nibbles.Count)
                            nibbles.Add(0);
                        nibbles[newlen++] = 0;
                        if (value < 0)
                            value = value * -1;
                    }
```

The unit test still pass.

**Comment by piranout** [comment] 2015-08-27 14:49
Can you give me a working way to reproduce it? That fix might not be valid if this were meant to be a general purpose base converter (for instance, can you reverse the conversion and get the same value back?). However, the base converter is really only included here to support Id generation. To do that, it only has to encode positive values: timestamps and integral random numbers. 

I would make that more explicit by throwing if `number`, `fromBase` or `toBase` are unfit for conversion (e.g. if `toBase` > `_charList.Length`), but this is one of the most called methods, and every additional check comes with a performance cost. Since the Id generator should never be throwing negative values, I might just make the BaseConverter class `internal`. Thoughts?

**Comment by piranout** [comment] 2015-11-11 15:39
I've made the involved methods `internal` to remove the possibility of attempting invalid, arbitrary base conversions. I'm closing this issue.

**Closed as completed by piranout** 2015-11-11 15:39 UTC
Labels: wontfix
